// Utility to generate seal template from current pose
export function generateSealTemplate(sealName, pose) {
  const capName = capitalize(sealName);

  // Formata os valores para 2 casas decimais
  const fmt = (v) => typeof v === 'number' ? parseFloat(v.toFixed(2)) : v;
  const fmtObj = (obj) => obj ? `{ x: ${fmt(obj.x)}, y: ${fmt(obj.y)}, z: ${fmt(obj.z)} }` : '{ x: 0, y: 0, z: 0 }';

  // Formata dedos
  const fmtFinger = (f, hasMid = true) => {
    if (hasMid) {
      return `{ base: ${fmtObj(f?.base)}, prox: ${fmtObj(f?.prox)}, mid: ${fmtObj(f?.mid)}, dist: ${fmtObj(f?.dist)} }`;
    }
    return `{ base: ${fmtObj(f?.base)}, prox: ${fmtObj(f?.prox)}, dist: ${fmtObj(f?.dist)} }`;
  };

  return `import { SealBase } from '../SealBase.js';

export class ${capName}Seal extends SealBase {
    getName() { return '${sealName.toLowerCase()}'; }

    getPose() {
        return {
            // Generated by ARVORE Pose Editor
            leftArm: {
                shoulder: ${fmtObj(pose.leftArm?.shoulder)},
                elbow: ${fmtObj(pose.leftArm?.elbow)},
                forearm: ${fmtObj(pose.leftArm?.forearm)}
            },
            rightArm: {
                shoulder: ${fmtObj(pose.rightArm?.shoulder)},
                elbow: ${fmtObj(pose.rightArm?.elbow)},
                forearm: ${fmtObj(pose.rightArm?.forearm)}
            },
            leftHand: {
                thumb: ${fmtFinger(pose.leftFingers?.thumb, false)},
                index: ${fmtFinger(pose.leftFingers?.index)},
                middle: ${fmtFinger(pose.leftFingers?.middle)},
                ring: ${fmtFinger(pose.leftFingers?.ring)},
                pinky: ${fmtFinger(pose.leftFingers?.pinky)}
            },
            rightHand: {
                thumb: ${fmtFinger(pose.rightFingers?.thumb, false)},
                index: ${fmtFinger(pose.rightFingers?.index)},
                middle: ${fmtFinger(pose.rightFingers?.middle)},
                ring: ${fmtFinger(pose.rightFingers?.ring)},
                pinky: ${fmtFinger(pose.rightFingers?.pinky)}
            },
            wrists: {
                left: ${fmtObj(pose.leftArm?.wrist)},
                right: ${fmtObj(pose.rightArm?.wrist)}
            }
        };
    }
}
`;
}

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();
}

// Copy template to clipboard
export function copyTemplateToClipboard(sealName, pose) {
  const template = generateSealTemplate(sealName, pose);
  navigator.clipboard.writeText(template).then(() => {
    alert(`Seal template for "${sealName}" copied to clipboard!`);
  }).catch(err => {
    console.error('Failed to copy:', err);
    alert('Failed to copy to clipboard');
  });
}

// Format pose for display
export function formatPoseForDisplay(pose) {
  return JSON.stringify(pose, (key, value) => {
    if (typeof value === 'number') {
      return parseFloat(value.toFixed(4));
    }
    return value;
  }, 2);
}
